### ISSUE TITLE
How to export aasx file into twins graph JSON?

### ISSUE THREAD

**Issue by mhlee0328** [JMayrbaeurl/opendigitaltwins-assetadminstrationshell#12]
Hi Team,

Could you please elaborate, from the AASX Package Explorer example "01_Festo.aasx", how to generate or export a huge twins graph /Sample/*.json like 
- 01_Festo ADTExplorer Export.json
- 01_Festo Linked ADTExplorer Export.json

what are the ways using which this requirement can be fulfilled?

Best Regards,
MinHao

**Comment by JMayrbaeurl** [comment]
Use the [AASX Command line tool](https://github.com/JMayrbaeurl/opendigitaltwins-aas-azureservices/blob/master/tools/aasx%20command%20line.md) to import the "01_Festo.aasx" file into an ADT instance and then use the [ADT Explorer](https://docs.microsoft.com/en-us/azure/digital-twins/concepts-azure-digital-twins-explorer#features-and-capabilities) to export the graph.
